version: '3.8'
services:
    redis:
        image: 'redis:alpine'
        container_name: news_review_redis_cache
        ports:
            - '6379:6379'
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
    postgres:
        image: postgres:9.6
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: newsreviewdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgres.conf:/etc/postgresql/postgresql.conf
        # command: postgres -c config_file=/etc/postgresql/postgresql.conf
